import { getDefaultConfig } from '@rainbow-me/rainbowkit'
import '@rainbow-me/rainbowkit/styles.css'
import {
  arbitrum,
  avalanche,
  base,
  bsc,
  degen,
  eos,
  fantom,
  gnosis,
  goerli,
  hardhat,
  localhost,
  mainnet,
  optimism,
  polygon,
  polygonMumbai,
  polygonZkEvm,
  sepolia,
  zkSync,
  zora,
} from 'wagmi/chains'

export const config = getDefaultConfig({
  appName: 'Vocdoni Voting Page',
  projectId: 'b78ba61f132db687dc6ec6d61b7e34d5',
  chains: [
    arbitrum,
    avalanche,
    base,
    bsc,
    degen,
    eos,
    fantom,
    gnosis,
    goerli,
    hardhat,
    localhost,
    mainnet,
    optimism,
    polygon,
    polygonMumbai,
    polygonZkEvm,
    sepolia,
    zkSync,
    zora,
  ],
})
